# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 02 Aug 2015 15:01:19 +0000
*	@ALL	2
event:linux_in_the_park_2016	@ALL	1
meeting:*	@user	8
operations:*	@operations	8
start	@admin	2
operations:meeting:*	@ALL	0
operations:meeting:*	@user	1
operations:meeting:*	@operations	8
