# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 02 Aug 2015 15:01:19 +0000
*	@ALL	2
meeting:*	@user	8
start	@admin	2
