<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: myles
 * Date: Wed, 01 Jun 2016 12:56:23 -0400
 */

$conf['title'] = 'GTALUG Wiki';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-zero';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'wiki-admin@gtalug.org';
$conf['mailfrom'] = 'hi@gtalug.org';
$conf['sitemap'] = 5;
$conf['userewrite'] = '1';
$conf['plugin']['piwik2']['track_admin_user'] = 1;
$conf['plugin']['piwik2']['js_tracking_code'] = '<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push([\'trackPageView\']);
  _paq.push([\'enableLinkTracking\']);
  (function() {
    var u="//piwik.gtalug.org/";
    _paq.push([\'setTrackerUrl\', u+\'piwik.php\']);
    _paq.push([\'setSiteId\', 1]);
    var d=document, g=d.createElement(\'script\'), s=d.getElementsByTagName(\'script\')[0];
    g.type=\'text/javascript\'; g.async=true; g.defer=true; g.src=u+\'piwik.js\'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//piwik.gtalug.org/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
';
$conf['plugin']['piwik2']['img_tracking_code'] = '<!-- Piwik Image Tracker-->
<img src="http://piwik.gtalug.org/piwik.php?idsite=1&rec=1" style="border:0" alt="" />
<!-- End Piwik -->';
$conf['plugin']['pagelist']['style'] = 'table';
$conf['plugin']['pagelist']['showheader'] = 1;
$conf['plugin']['pagelist']['showdesc'] = '160';
$conf['plugin']['pagelist']['sort'] = 1;
$conf['plugin']['captcha']['loginprotect'] = 1;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'optional';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cosmo';
$conf['tpl']['bootstrap3']['semantic'] = 1;
$conf['tpl']['bootstrap3']['showBadges'] = 0;
$conf['tpl']['bootstrap3']['showLoginOnFooter'] = 1;
$conf['tpl']['bootstrap3']['useGravatar'] = 1;
$conf['tpl']['bootstrap3']['tocAffix'] = 0;
$conf['tpl']['bootstrap3']['pageInfoDateFormat'] = 'human';
$conf['tpl']['bootstrap3']['showPageIcons'] = 1;

// end auto-generated content
