<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: myles
 * Date: Sun, 02 Aug 2015 16:20:44 +0000
 */

$conf['title'] = 'GTALUG Wiki';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-zero';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = '1';
$conf['plugin']['piwik2']['track_admin_user'] = 1;
$conf['plugin']['piwik2']['js_tracking_code'] = '<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push([\'trackPageView\']);
  _paq.push([\'enableLinkTracking\']);
  (function() {
    var u="//piwik.gtalug.org/";
    _paq.push([\'setTrackerUrl\', u+\'piwik.php\']);
    _paq.push([\'setSiteId\', 1]);
    var d=document, g=d.createElement(\'script\'), s=d.getElementsByTagName(\'script\')[0];
    g.type=\'text/javascript\'; g.async=true; g.defer=true; g.src=u+\'piwik.js\'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//piwik.gtalug.org/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
';
$conf['plugin']['piwik2']['img_tracking_code'] = '<!-- Piwik Image Tracker-->
<img src="http://piwik.gtalug.org/piwik.php?idsite=1&rec=1" style="border:0" alt="" />
<!-- End Piwik -->';
$conf['plugin']['captcha']['loginprotect'] = 1;
$conf['tpl']['bootstrap3']['semantic'] = 1;
$conf['tpl']['bootstrap3']['showBadges'] = 0;

// end auto-generated content
